### ISSUE TITLE
pg-info: Should collect trigger info too

### ISSUE THREAD

**Issue by timneedham** [wmfs/tymly#55]
# Enhancement to pg-info

Our [pg-info](https://github.com/wmfs/tymly/tree/9efd85d3856fc3a0c64c683baab16410156b7130/packages/pg-info) package collates various pieces of information from a specified set of schemas within a PostgreSQL database.

__You'll see that currently, information about:__

* Schemas
* Tables
* Columns
* Indexes
* Foreign key constraints

... is all bundled in the returned `info` object.

We now require to include details about any triggers defined against the triggers (in much the same way as index definitions are included).

## Thoughts

From an initial search, it seems everything we need is available via the `information_schema.triggers` view.

And so it is a matter of adding an appropriate query:

https://github.com/wmfs/tymly/blob/master/packages/pg-info/lib/index.js#L20-L87

And ensuring a new `triggers` object is included as required for each table.

* It should behave in a consist way as compared with indexes (i.e. a new `triggers` property should appear within a `table` object... where the keys of a `triggers` object is the name of a trigger `trigger_name`, and the value is a `trigger` object).
* A `trigger` object should include _just_ the pertinent information about the trigger as available in `information_schema.triggers`, suggestions:

  * `event_object_schema`
  * `event_manipulation`
  * `event_object_table`
  * `action_condition`
  * `action_statement`
  * `action_orientation`
  * `action_timing`

* Please ensure the [README.md of the pg-info package](https://github.com/wmfs/tymly/tree/master/packages/pg-info#index-object) is changed to reflect the new `triggers` property and `trigger` object.
* Please ensure the tests return expected trigger information against at least one table.

**Comment by meenahoda** [comment]
https://github.com/wmfs/tymly/commit/43ad1e71699f3d2ba3d508184ee875102f08ae03
https://github.com/wmfs/tymly/commit/51842bbb070f472f96ed2497b1e0c6c2b242dde5

When creating a test trigger to work with, it's only currently possibly by doing directly in client.query(...) rather than being in the install-test-schemas script. This is because we pass the script through client.runFile(...) and in this function it initially splits everything by ';' 
https://github.com/wmfs/tymly/blob/master/packages/hl-pg-client/lib/index.js#L32
meaning the inside of the 'create function' bit gets split and causes a syntax error when trying to run the split queries.
